language: go
install:
- go get -v github.com/spf13/hugo
- pip install --user awscli
script:
- hugo version
- make deploy
branches:
  only:
  - master
env:
  global:
  - secure: rh15qWNMJiR2AWc/HozI4OBPOUeaSt1vV1v5DPkZbpHDSOm8C3TvsqM9lSsALXYvUXXZOfFTdFWNGO04Q7X6H9dwLnlyhNhGAJ+xixDfRWR0p5aiyZMm17zZLO1Zmc6/gG3uIlctacrSXIvoCOLRbHvpYmJycY6NJxd4QWt2Jadz3kkptRByW8AHJckzYByxkhM4UoKGyxT9KGJVW7V2pbCpGd2ZXPGAIg41Kq8XSwgOFPyOiMEUqeG/T3gXvlHCWGSlyjD9dh+1SwM0CayOgyvRocpSTQr2A5m3PsV89mRM5WwMS7kRFAksX4voaakp0c17Hcn6kZzRJxkswHaA3w+NhHgC9FbUoReGzQkb5wRPgIoKNlPXj0rIk3cvERp3gLEF2ysaMxkw4Oqz786VNFWt0v+GGdWJtOY01mzh+ixLeq/UaBkE3QrHZ5+uC+Ni8ZZqVpKREyRPJ2Pzpg9muQtTzFD5aAFOYvUovOmsk4wo6U+KleeJcXQIUL/ooijqO4QMhE9HxtDTiFBy/k53XdDW9GtfRMQzrXJaTikSLnYrPSsg+M/qqCK2ZgqbezRM06mgjYjmX89DIU2NA7BTY/F8NFhpxc/NGj1eKWwgcTUImqCwbDp1GI/weeJFe1hZOLnXXsMZAOgL8447ytZ+qFCjdlGrYGeU1ifucsF02g8=
  - secure: thTgK4MsmuAoIqKq9pDBveNgOQug8MOneNNIOrIPnSESWUdZTUVmpJLWaBG/FoS6abQYO1+X0OCHtaIVqRnKTMwbxZB45WboZhOQ1qJaXAC3OWdApORNolXEp9LIFx/WbGT4ZkzXLI+MvRA334PEUK+JNs1FYQ/pqqsgTTmJT/3AC5XgDo2ZwNzSofdiUSbI4bYxB1Y/3aXMQQtPlPKt4/Kt6/N9TdzD1T37mEx5QIpl9pb7sOGqLAu2YDzH8V+G/QLOE6BFMpuXrhxejxT3IGcugSMjg9uUndx2iSW+gr+zHVmwEp9qgqGcjNNb+V4Gg9a4ogrbb/pJfqy4jpQHV+6ND0Ye9131XVybLkPY5aoSsG/EhNtdBmQ76+njx60ZPG5HnETFCALMbcaIIlhdcpr8BG9JoJLjqzb9t3Spc9SRWDC9Ioqa3BaXAgP9Aq7T46Kk8Qi22zpGvVkSJQvu0Xd3Y8jG5w0bxnbBUfftjfr+Cxt56S0uS8C8Dg8qswqmwGNCKAxyxTrw5FGdpQO61lebAEYxsxX8VwDpSoIqEHheOSMLk4cmcj6g3Fyrqzarsm74xjoftgOw0ODSVsQ62b1L0CLP/mhJsMHjeuCPia9BMSfE5ickiKTaGAx0BIkNxXPeT4nCJFwDLI1cDTUSjlgeeE8XKR1s/RqJ8S9ewPE=
